POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "password"
}

###

GET http://localhost:3000/user/deec3e06-9efe-4634-b2cf-674f37d032ed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZWVjM2UwNi05ZWZlLTQ2MzQtYjJjZi02NzRmMzdkMDMyZWQiLCJmaXJzdE5hbWUiOiJJbGxpYSIsImxhc3ROYW1lIjoiVHNhcHUiLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzM3NTI4ODU0LCJleHAiOjE3Mzc1Mjg4ODR9.eTYGzC-VBV4F6fVwb62XDh0pp7pCPpd9TI3td507-f0