name: Linter & Build check

on: push

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    container:
      image: node:20
    outputs:
      cache-key: ${{ steps.set-key.outputs.key }}
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Generate cache key
        id: set-key
        run: echo "key=deps-${{ hashFiles('package-lock.json') }}" >> $GITHUB_OUTPUT

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ steps.set-key.outputs.key }}

      - name: Install dependencies
        run: npm i

  run-linter:
    needs: install-dependencies
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ needs.install-dependencies.outputs.cache-key }}

      - run: npm run lint

  build:
    needs: install-dependencies
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ needs.install-dependencies.outputs.cache-key }}

      - run: npm run build
